language: julia
os:
  - windows
  - linux
  - osx
julia:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - nightly
matrix:
  allow_failures:
    - julia: 1.1
    - julia: 1.2
    - julia: 1.4
    - julia: nightly
notifications:
  email: false
after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("HalfEdges")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
